CREATE TABLE [dbo].[Features]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Naziv NVARCHAR(150) NOT NULL,
	Description TEXT,
	Approved BIT,
	UserId BIGINT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	ReleaseId  BIGINT FOREIGN KEY REFERENCES Releases(Id) NOT NULL
)
